// Generated by WebGPU-KTypes WGSL Backend

fn add_f32(a: f32, b: f32) -> f32 {
    
}

fn sub_f32(a: f32, b: f32) -> f32 {
    
}

fn mul_f32(a: f32, b: f32) -> f32 {
    
}

fn div_f32(a: f32, b: f32) -> f32 {
    
}

fn rem_f32(a: f32, b: f32) -> f32 {
    
}

fn vs_main(pos: vec2<f32>) -> vec4<f32> {
    
}

@vertex
fn vs_main() -> vec4<f32> {
}
