// Generated by WebGPU-KTypes WGSL Backend
var<private> global_0: i32;

fn vs_main(pos: vec3<f32>) -> vec4<f32> {
    global_0 = (global_0 + 1);
    return vec4<f32>(pos, 1.0f);
}

@vertex
fn vs_main() -> vec4<f32> {
}
