// Generated by WebGPU-KTypes WGSL Backend
var<private> global_0: i32;
var<workgroup> global_1: /* unknown type */;

fn vs_main(pos: vec3<f32>) -> vec4<f32> {
    
}

fn fs_main() -> vec4<f32> {
    
}

@vertex
fn vs_main() -> vec4<f32> {
}

@fragment
fn fs_main() -> vec4<f32> {
}
