// Generated by WebGPU-KTypes WGSL Backend

fn vs_main(in_vertex_index: u32) -> vec4<f32> {
    
}

fn fs_main() -> vec4<f32> {
    
}

@vertex
fn vs_main() -> vec4<f32> {
}

@fragment
fn fs_main() -> vec4<f32> {
}
