// Generated by WebGPU-KTypes WGSL Backend

fn vs_main(in_vertex_index: u32) -> vec4<f32> {
    f32 local_0 = f32((i32(in_vertex_index) - 1));
    f32 local_1 = f32(((i32((in_vertex_index & 0u)) * 2) - 1));
    return vec4<f32>(local_0, local_1, 0.0f, 1.0f);
}

@vertex
fn vs_main() -> vec4<f32> {
}
