package io.ygdrasil.wgsl.wgsl

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.string.shouldContain
import io.ygdrasil.wgsl.arena.Arena
import io.ygdrasil.wgsl.ir.Block
import io.ygdrasil.wgsl.ir.Expression
import io.ygdrasil.wgsl.ir.Function
import io.ygdrasil.wgsl.ir.Module
import io.ygdrasil.wgsl.ir.ScalarKind
import io.ygdrasil.wgsl.ir.StructMember
import io.ygdrasil.wgsl.ir.Type
import io.ygdrasil.wgsl.ir.TypeInner

class WgslWriterTest : FunSpec({

    test("testEmptyModule") {
        val module = Module()
        val code = WgslModule.writeString(module)
        code shouldContain "// Generated by WebGPU-KTypes WGSL Backend"
    }

    test("testModuleWithStructAndFunction") {
        val module = Module()

        // Add a scalar type
        val f32Handle = module.types.append(Type(TypeInner.Scalar(ScalarKind.F32, 4)))

        // Add a struct
        module.types.append(
            Type(
                TypeInner.Struct(
                    listOf(
                        StructMember("a", f32Handle, null, 0)
                    )
                )
            )
        )

        // Add a function
        val expressions = Arena<Expression>()
        val blocks = Arena<Block>()
        val body = blocks.append(Block(emptyList()))

        module.functions.append(
            Function(
                name = "my_func",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "struct Struct_1"
        code shouldContain "a: f32"
        code shouldContain "fn my_func()"
    }
})