// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


float add_f32(float a, float b) {
    
}

float sub_f32(float a, float b) {
    
}

float mul_f32(float a, float b) {
    
}

float div_f32(float a, float b) {
    
}

float rem_f32(float a, float b) {
    
}

float4 vs_main(float2 pos) {
    
}

struct vs_main_Output {
    float4 position : SV_Position;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return stage_out;
}
