// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


float4 vs_main() {
    float local_0 = 0;
    
    float local_0 = 0;
    return float(0, local_0);
}

struct vs_main_Output {
    float4 position : SV_Position;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return stage_out;
}
