// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

int global_0;

float4 vs_main(float3 pos) {
    global_0 = (global_0 + 1);
    return float4(pos, 1.0f);
}

struct vs_main_Output {
    float4 position : SV_Position;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return stage_out;
}
