// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

int global_0;
void global_1;

float4 vs_main(float3 pos) {
    
}

float4 fs_main() {
    
}

struct vs_main_Output {
    float4 position : SV_Position;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return stage_out;
}

float4 fs_main() {
}
