// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


float4 vs_main(uint in_vertex_index) {
    float local_0 = float((float(in_vertex_index) - 1));
    float local_1 = float(((float((in_vertex_index & 0u)) * 2) - 1));
    
    float local_0 = float((float(in_vertex_index) - 1));
    float local_1 = float(((float((in_vertex_index & 0u)) * 2) - 1));
    return float(local_0, local_1, 0.0f, 1.0f);
}

float4 fs_main() {
    
    return float(1.0f, 0.0f, 0.0f, 1.0f);
}

struct vs_main_Output {
    float4 position : SV_Position;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return stage_out;
}

float4 fs_main() {
}
