// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


float4 vs_main(uint in_vertex_index) {
    
}

float4 fs_main() {
    
}

struct vs_main_Output {
    float4 position : SV_Position;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return stage_out;
}

float4 fs_main() {
}
