// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_0 {
};
Struct_0 global_0;
Struct_0 global_1;

void main(uint3 id) {
    
}

[numthreads(1, 1, 1)]
void main() {
}
