package io.ygdrasil.wgsl.hlsl

import io.ygdrasil.wgsl.arena.Handle
import io.ygdrasil.wgsl.back.HlslOptions
import io.ygdrasil.wgsl.back.WriterBase
import io.ygdrasil.wgsl.back.BackendWriter
import io.ygdrasil.wgsl.ir.*
import io.ygdrasil.wgsl.ir.Function
import io.ygdrasil.wgsl.proc.Layouter
import io.ygdrasil.wgsl.proc.Namer
import io.ygdrasil.wgsl.valid.ModuleInfo

class HlslWriter(
    output: StringBuilder,
    module: Module,
    moduleInfo: ModuleInfo,
    options: HlslOptions,
    namer: Namer,
    layouter: Layouter
) : WriterBase<HlslOptions>(output, module, moduleInfo, options, namer, layouter), BackendWriter<HlslOptions> {

    override fun write(module: Module, moduleInfo: ModuleInfo): String {
        return write()
    }

    override fun withOptions(options: HlslOptions): BackendWriter<HlslOptions> {
        return HlslWriter(StringBuilder(), module, moduleInfo, options, namer, layouter)
    }

    override fun canHandle(module: Module, moduleInfo: ModuleInfo): Boolean = true

    override fun writeHeader() {
        writeLine("// Generated by WebGPU-KTypes HLSL Backend")
    }

    override fun writeStructType(handle: Handle<Type>, structInner: TypeInner.Struct, name: String) {
        writeLine("struct $name {")
        indent {
            for (member in structInner.members) {
                val memberName = member.name
                val typeName = getTypeName(member.type)
                writeLine("$typeName $memberName;")
            }
        }
        writeLine("};")
    }

    override fun writeFunctionSignature(func: Function, name: String) {
        val returnType = func.returnType?.let { getTypeName(it) } ?: "void"
        write("$returnType $name(")
        func.parameters.forEachIndexed { i, param ->
            if (i > 0) write(", ")
            val typeName = getTypeName(param.type)
            write("$typeName ${param.name}")
        }
        write(")")
    }

    override fun writeEntryPoint(ep: EntryPoint, index: Int) {
        writeLine("// Entry point: ${ep.name}")
        val func = module.functions[ep.function]
        writeFunctionSignature(func, ep.name)
        writeLine(" {")
        indent {
            writeBlock(func.body)
        }
        writeLine("}")
    }

    override fun getScalarTypeName(scalar: TypeInner.Scalar): String {
        return when (scalar.kind) {
            ScalarKind.Bool -> "bool"
            ScalarKind.Sint -> "int"
            ScalarKind.Uint -> "uint"
            ScalarKind.F32 -> "float"
            ScalarKind.F16 -> "half"
            ScalarKind.F64 -> "double"
            else -> "void"
        }
    }

    override fun getTypeName(handle: Handle<Type>): String {
        val type = module.types[handle]
        return when (val inner = type.inner) {
            is TypeInner.Scalar -> getScalarTypeName(inner)
            is TypeInner.Vector -> {
                val scalarType = module.types[inner.scalar]
                val scalarName = getScalarTypeName(scalarType.inner as TypeInner.Scalar)
                "$scalarName${inner.size.ordinal + 2}"
            }
            is TypeInner.Matrix -> {
                val scalarType = module.types[inner.scalar]
                val scalarName = getScalarTypeName(scalarType.inner as TypeInner.Scalar)
                "$scalarName${inner.columns.ordinal + 2}x${inner.rows.ordinal + 2}"
            }
            is TypeInner.Struct -> "Struct_${handle.index}"
            is TypeInner.Pointer -> {
                val baseName = getTypeName(inner.base)
                // Simplified HLSL pointer mapping
                "$baseName*"
            }
            else -> "void"
        }
    }

    override fun getBuiltinFunctionName(function: BuiltinFunction): String = when (function) {
        BuiltinFunction.Ln -> "log"
        BuiltinFunction.Mix -> "lerp"
        BuiltinFunction.Fract -> "frac"
        else -> super.getBuiltinFunctionName(function)
    }
}
