package io.ygdrasil.wgsl.wgsl

import io.ygdrasil.wgsl.arena.Handle
import io.ygdrasil.wgsl.back.WgslOptions
import io.ygdrasil.wgsl.back.WriterBase
import io.ygdrasil.wgsl.back.BackendWriter
import io.ygdrasil.wgsl.ir.*
import io.ygdrasil.wgsl.ir.Function
import io.ygdrasil.wgsl.proc.Layouter
import io.ygdrasil.wgsl.proc.Namer
import io.ygdrasil.wgsl.valid.ModuleInfo

class WgslWriter(
    output: StringBuilder,
    module: Module,
    moduleInfo: ModuleInfo,
    options: WgslOptions,
    namer: Namer,
    layouter: Layouter
) : WriterBase<WgslOptions>(output, module, moduleInfo, options, namer, layouter), BackendWriter<WgslOptions> {

    override fun write(module: Module, moduleInfo: ModuleInfo): String {
        return WgslWriter(StringBuilder(), module, moduleInfo, options, namer, layouter).write()
    }

    override fun withOptions(options: WgslOptions): BackendWriter<WgslOptions> {
        return WgslWriter(StringBuilder(), module, moduleInfo, options, namer, layouter)
    }

    override fun canHandle(module: Module, moduleInfo: ModuleInfo): Boolean = true

    override fun writeHeader() {
        writeLine("// Generated by WebGPU-KTypes WGSL Backend")
    }

    override fun writeStructType(handle: Handle<Type>, structInner: TypeInner.Struct, name: String) {
        writeLine("struct $name {")
        indent {
            for (member in structInner.members) {
                val memberName = member.name
                val typeName = getTypeName(member.type)
                writeLine("$memberName: $typeName,")
            }
        }
        writeLine("}")
    }

    override fun writeFunctionSignature(func: Function, name: String) {
        val returnType = func.returnType?.let { " -> ${getTypeName(it)}" } ?: ""
        write("fn $name(")
        func.parameters.forEachIndexed { i, param ->
            if (i > 0) write(", ")
            val typeName = getTypeName(param.type)
            write("${param.name}: $typeName")
        }
        write(")$returnType")
    }

    override fun writeGlobalVariables() {
        module.globalVariables.forEachWithHandle { handle, variable ->
            val name = getGlobalVariableName(handle)
            val typeName = getTypeName(variable.type)
            val binding = variable.binding
            if (binding != null) {
                writeLine("@group(${binding.group}) @binding(${binding.index})")
            }
            val space = when (variable.storageClass) {
                StorageClass.Uniform -> "<uniform>"
                StorageClass.Storage -> {
                    val mode = when (variable.accessMode) {
                        AccessMode.Read -> ", read"
                        AccessMode.Write -> ", write"
                        AccessMode.ReadWrite -> ", read_write"
                        null -> ""
                    }
                    "<storage$mode>"
                }
                StorageClass.Workgroup -> "<workgroup>"
                StorageClass.Private -> "<private>"
                StorageClass.PushConstant -> "<push_constant>"
                StorageClass.Function -> "<function>"
                StorageClass.Handle -> ""
            }
            val init = variable.init?.let { " = ${writeExpression(it)}" } ?: ""
            writeLine("var$space $name: $typeName$init;")
        }
    }

    override fun writeEntryPoint(ep: EntryPoint, index: Int) {
        writeLine()
        val stage = ep.stage.name.lowercase()
        writeLine("@$stage")
        val func = module.functions[ep.function]
        val returnType = func.returnType?.let { " -> ${getTypeName(it)}" } ?: ""
        
        write("fn ${ep.name}(")
        
        val args = mutableListOf<String>()
        
        ep.bindings.forEach { attr ->
            when (attr) {
                is BindingAttribute.Builtin -> {
                    val typeName = getWgslBuiltinType(attr.builtin)
                    val name = attr.builtin.name.lowercase()
                    args.add("@builtin(${getWgslBuiltinName(attr.builtin)}) $name: $typeName")
                }
                is BindingAttribute.Location -> {
                    val typeName = "vec4<f32>" 
                    val name = "loc_${attr.location}"
                    args.add("@location(${attr.location}) $name: $typeName")
                }
                else -> {}
            }
        }

        write(args.joinToString(", "))
        writeLine(")$returnType {")
        indent {
            writeBlock(func.body)
        }
        writeLine("}")
    }

    override fun writeExpression(handle: Handle<Expression>): String {
        val expr = if (currentFunction != null) {
            currentFunction!!.expressions[handle]
        } else {
            module.globalExpressions[handle]
        }

        if (expr.kind is ExpressionKind.ArrayLength) {
            val e = writeExpression((expr.kind as ExpressionKind.ArrayLength).expr)
            return "arrayLength(&$e)"
        }
        
        return super.writeExpression(handle)
    }

    override fun writeSample(
        texture: String,
        sampler: String?,
        coordinate: String,
        level: SampleLevel?,
        depthRef: Handle<Expression>?
    ): String {
        return "textureSample($texture, ${sampler ?: "/* no sampler */"}, $coordinate)"
    }

    override fun writeTextureQuery(texture: String, query: TextureQueryKind): String {
        val method = when (query) {
            TextureQueryKind.Size -> "textureDimensions($texture)"
            TextureQueryKind.SizeLevel -> "textureDimensions($texture, level)" // TODO: level
            TextureQueryKind.NumLevels -> "textureNumLevels($texture)"
            TextureQueryKind.NumLayers -> "textureNumLayers($texture)"
            TextureQueryKind.NumSamples -> "textureNumSamples($texture)"
        }
        return method
    }

    private fun getWgslBuiltinName(builtin: BuiltinValue): String = when (builtin) {
        BuiltinValue.VertexIndex -> "vertex_index"
        BuiltinValue.InstanceIndex -> "instance_index"
        BuiltinValue.LocalInvocationId -> "local_invocation_id"
        BuiltinValue.LocalInvocationIndex -> "local_invocation_index"
        BuiltinValue.GlobalInvocationId -> "global_invocation_id"
        BuiltinValue.WorkgroupId -> "workgroup_id"
        BuiltinValue.NumWorkgroups -> "num_workgroups"
        else -> builtin.name.lowercase()
    }

    private fun getWgslBuiltinType(builtin: BuiltinValue): String = when (builtin) {
        BuiltinValue.Position -> "vec4<f32>"
        BuiltinValue.VertexIndex, BuiltinValue.InstanceIndex, BuiltinValue.SampleIndex -> "u32"
        BuiltinValue.FrontFacing -> "bool"
        BuiltinValue.LocalInvocationId, BuiltinValue.GlobalInvocationId, 
        BuiltinValue.WorkgroupId, BuiltinValue.NumWorkgroups -> "vec3<u32>"
        BuiltinValue.LocalInvocationIndex, BuiltinValue.SampleMask -> "u32"
        else -> "u32"
    }

    override fun getScalarTypeName(scalar: TypeInner.Scalar): String {
        return when (scalar.kind) {
            ScalarKind.Bool -> "bool"
            ScalarKind.Sint -> "i32"
            ScalarKind.Uint -> "u32"
            ScalarKind.F32 -> "f32"
            ScalarKind.F16 -> "f16"
            ScalarKind.F64 -> "f64"
            else -> "/* unknown scalar */"
        }
    }

    override fun getTypeName(handle: Handle<Type>): String {
        val type = module.types[handle]
        return when (val inner = type.inner) {
            is TypeInner.Scalar -> getScalarTypeName(inner)
            is TypeInner.Vector -> {
                val scalarType = module.types[inner.scalar]
                val scalarName = getScalarTypeName(scalarType.inner as TypeInner.Scalar)
                "vec${inner.size.ordinal + 2}<$scalarName>"
            }
            is TypeInner.Matrix -> {
                val scalarType = module.types[inner.scalar]
                val scalarName = getScalarTypeName(scalarType.inner as TypeInner.Scalar)
                "mat${inner.columns.ordinal + 2}x${inner.rows.ordinal + 2}<$scalarName>"
            }
            is TypeInner.Struct -> "Struct_${handle.index}"
            is TypeInner.Pointer -> {
                val baseName = getTypeName(inner.base)
                val space = inner.addressSpace.name.lowercase()
                val mode = when (inner.accessMode) {
                    AccessMode.Read -> ", read"
                    AccessMode.Write -> ", write"
                    AccessMode.ReadWrite -> ", read_write"
                    null -> ""
                }
                "ptr<$space, $baseName$mode>"
            }
            is TypeInner.Opaque -> inner.name
            else -> "/* unknown type */"
        }
    }

    override fun writeRelational(function: RelationalFunction, arguments: List<String>): String {
        return "${function.name.lowercase()}(${arguments.joinToString()})"
    }

    override fun writeAtomic(pointer: String, function: AtomicFunction, arguments: List<String>): String {
        val wgslFunc = when (function) {
            AtomicFunction.Add -> "atomicAdd"
            AtomicFunction.Subtract -> "atomicSub"
            AtomicFunction.And -> "atomicAnd"
            AtomicFunction.Or -> "atomicOr"
            AtomicFunction.Xor -> "atomicXor"
            AtomicFunction.Min -> "atomicMin"
            AtomicFunction.Max -> "atomicMax"
            AtomicFunction.Exchange -> "atomicExchange"
            AtomicFunction.CompSwap -> "atomicCompareExchangeWeak"
        }
        return "$wgslFunc($pointer, ${arguments.joinToString()})"
    }

    override fun getBuiltinFunctionName(function: BuiltinFunction): String = when (function) {
        BuiltinFunction.Ln -> "log"
        else -> super.getBuiltinFunctionName(function)
    }
}
