package io.ygdrasil.wgsl.back.wgsl

import io.ygdrasil.wgsl.arena.Handle
import io.ygdrasil.wgsl.back.WgslOptions
import io.ygdrasil.wgsl.back.WriterBase
import io.ygdrasil.wgsl.back.BackendWriter
import io.ygdrasil.wgsl.ir.*
import io.ygdrasil.wgsl.ir.Function
import io.ygdrasil.wgsl.proc.Layouter
import io.ygdrasil.wgsl.proc.Namer
import io.ygdrasil.wgsl.valid.ModuleInfo

class WgslWriter(
    output: StringBuilder,
    module: Module,
    moduleInfo: ModuleInfo,
    options: WgslOptions,
    namer: Namer,
    layouter: Layouter
) : WriterBase<WgslOptions>(output, module, moduleInfo, options, namer, layouter), BackendWriter<WgslOptions> {

    override fun write(module: Module, moduleInfo: ModuleInfo): String {
        return write()
    }

    override fun withOptions(options: WgslOptions): BackendWriter<WgslOptions> {
        return WgslWriter(StringBuilder(), module, moduleInfo, options, namer, layouter)
    }

    override fun canHandle(module: Module, moduleInfo: ModuleInfo): Boolean = true

    override fun writeHeader() {
        writeLine("// Generated by WebGPU-KTypes WGSL Backend")
    }

    override fun writeStructType(handle: Handle<Type>, structInner: TypeInner.Struct, name: String) {
        writeLine("struct $name {")
        indent {
            for (member in structInner.members) {
                val memberName = member.name
                val typeName = getTypeName(member.type)
                writeLine("  $memberName: $typeName,")
            }
        }
        writeLine("}")
    }

    override fun writeFunctionSignature(func: Function, name: String) {
        val returnType = func.returnType?.let { " -> ${getTypeName(it)}" } ?: ""
        write("fn $name(")
        func.parameters.forEachIndexed { i, param ->
            if (i > 0) write(", ")
            val typeName = getTypeName(param.type)
            write("${param.name}: $typeName")
        }
        write(")$returnType")
    }

    override fun writeEntryPoint(ep: EntryPoint, index: Int) {
        writeLine()
        val stage = ep.stage.name.lowercase()
        writeLine("@$stage")
        val func = module.functions[ep.function]
        writeFunctionSignature(func, ep.name)
        writeLine(" {")
        indent {
            writeBlock(func.body)
        }
        writeLine("}")
    }

    override fun getScalarTypeName(scalar: TypeInner.Scalar): String {
        return when (scalar.kind) {
            ScalarKind.Bool -> "bool"
            ScalarKind.Sint -> "i32"
            ScalarKind.Uint -> "u32"
            ScalarKind.F32 -> "f32"
            ScalarKind.F16 -> "f16"
            ScalarKind.F64 -> "f64"
            else -> "/* unknown scalar */"
        }
    }

    override fun getTypeName(handle: Handle<Type>): String {
        val type = module.types[handle]
        return when (val inner = type.inner) {
            is TypeInner.Scalar -> getScalarTypeName(inner)
            is TypeInner.Vector -> {
                val scalarName = getScalarTypeName(module.types[inner.scalar].inner as TypeInner.Scalar)
                "vec${inner.size.ordinal + 2}<$scalarName>"
            }
            is TypeInner.Matrix -> {
                val scalarName = getScalarTypeName(module.types[inner.scalar].inner as TypeInner.Scalar)
                "mat${inner.columns.ordinal + 2}x${inner.rows.ordinal + 2}<$scalarName>"
            }
            is TypeInner.Struct -> "Struct_${handle.index}"
            else -> "/* unknown type */"
        }
    }
}
