name: Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Android SDK (platform 35)
        uses: android-actions/setup-android@v3

      - name: Install Android platform 35 (for AGP configuration)
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager --install "platforms;android-35" "build-tools;35.0.0"

      - name: Set up Chrome for headless browser tests
        uses: browser-actions/setup-chrome@v1

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests (Gradle check)
        run: ./gradlew --no-daemon --stacktrace --info check

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Test Report
          path: '**/build/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: false
          list-suites: true
          list-tests: failed

      - name: Upload test results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          if-no-files-found: warn
          retention-days: 7
          path: |
            **/build/test-results/**
            **/build/reports/tests/**
